library:
  source-dirs: src
tests:
  aoc2018-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018
copyright: 2018 Author name here
maintainer: example@example.com
dependencies:
- text
- base >= 4.7 && < 5
- MissingH
- lens
- split
- containers
name: aoc2018
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/aoc2018
license: BSD3
executables:
  aoc2018-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2018
description: Please see the README on GitHub at <https://github.com/githubuser/aoc2018#readme>
